export const adminCopy = {
  pl: {
    locale: "pl-PL",
    currency: "zł",
    supabaseMissing: "Supabase nie jest skonfigurowany dla tego wdrożenia.",
    permissionsFailed: "Nie udało się sprawdzić uprawnień konta.",
    dashboardLoadFailed: "Nie udało się pobrać danych dyspozytora.",
    loginFailed: "Nie udało się zalogować.",
    tripSaveFailed: "Nie udało się zapisać kursu.",
    bookingSaveFailed: "Nie udało się zapisać rezerwacji.",
    roleSaveFailed: "Nie udało się zapisać roli.",
    bookingStatusSaved: "Status rezerwacji zapisany.",
    profileRoleSaved: "Rola użytkownika zapisana.",
    checkingAccessTitle: "Sprawdzanie dostępu",
    checkingAccessBody: "Ładowanie sesji dyspozytora.",
    operationsEyebrow: "Contbus Operacje",
    dashboardTitle: "Panel dyspozytora",
    navDashboard: "Panel",
    navSchedules: "Rozkłady",
    loginIntro: "Zaloguj się kontem z rolą dispatcher albo admin.",
    email: "Email",
    password: "Hasło",
    signingIn: "Logowanie...",
    signIn: "Zaloguj",
    noAccessEyebrow: "Brak dostępu",
    noAccessTitle: "To konto nie jest dyspozytorem",
    noAccessBody: "Poproś administratora Supabase o ustawienie roli profilu na dispatcher albo admin.",
    logout: "Wyloguj",
    heroBody:
      "Dzisiejsze kursy, obłożenie i sprzedaż z tej samej bazy, której używa strona, aplikacja klienta i aplikacja kierowcy.",
    refresh: "Odśwież",
    aggregateWarning: "Widok sprzedaży czeka na aktywację agregatów dyspozytora w Supabase.",
    trips: "Kursy",
    bookings: "Rezerwacje",
    passengers: "Pasażerowie",
    sales: "Sprzedaż",
    activeRoutes: "Aktywne trasy",
    vehicles: "Pojazdy",
    notCancelled: "bez anulowanych",
    selectedDay: "na wybrany dzień",
    paidDemo: "płatności testowe",
    staffAuthHint: "po włączeniu dostępu personelu",
    operations: "Operacje",
    tripControl: "Sterowanie kursem",
    dispatcherOps: "Operacje dyspozytora",
    status: "Status",
    vehicle: "Pojazd",
    driver: "Kierowca",
    platform: "Peron",
    assignPending: "Do przypisania",
    platformPlaceholder: "np. Peron 3",
    tripStatusSaved: "Status kursu zapisany.",
    vehicleAssigned: "Pojazd przypisany.",
    driverAssigned: "Kierowca przypisany.",
    platformSaved: "Peron zapisany.",
    revenue: "Przychód",
    incidents: "Incydenty",
    tripManifest: "Manifest kursu",
    noBookingsOnTrip: "Brak rezerwacji na tym kursie.",
    chooseTrip: "Wybierz kurs z listy operacyjnej.",
    search: "Wyszukiwarka",
    searchPlaceholder: "Kod, email, nazwisko...",
    noMatchingBookings: "Brak pasujących rezerwacji.",
    access: "Dostęp",
    userRoles: "Role użytkowników",
    unnamed: "Bez nazwy",
    today: "Dzisiaj",
    operationalTrips: "Kursy operacyjne",
    busiest: "Największe obłożenie:",
    loadingTrips: "Ładowanie kursów...",
    noTripsForDate: "Brak kursów dla tej daty.",
    noPlatform: "Bez peronu",
    vehicleUnassigned: "Pojazd do przypisania",
    driverUnassigned: "Kierowca do przypisania",
    reservationsShort: "rez.",
    routes: "Trasy",
    salesByRoute: "Sprzedaż wg tras",
    routeTrips: "kursy",
    recentBookings: "Ostatnie rezerwacje",
    noVisibleBookings: "Brak widocznych rezerwacji.",
    passengersShort: "pas.",
    checkedIn: "odprawionych",
    commandCenter: "Centrum dowodzenia",
    commandCenterLead: "Najważniejsze ryzyka, gotowość załogi i postęp odprawy w jednym miejscu.",
    attentionQueue: "Wymaga uwagi",
    noAttentionItems: "Brak krytycznych zadań dla wybranego dnia.",
    delayedTrips: "Opóźnione kursy",
    missingVehicles: "Kursy bez pojazdu",
    missingDrivers: "Kursy bez kierowcy",
    missingPlatforms: "Kursy bez peronu",
    highOccupancy: "Kursy powyżej 85% obłożenia",
    activeIncidents: "Aktywne incydenty",
    fixNow: "Otwórz kurs",
    readiness: "Gotowość operacyjna",
    checkInProgress: "Postęp odprawy",
    fleetAssigned: "Flota przypisana",
    driversAssigned: "Kierowcy przypisani",
    platformReady: "Perony gotowe",
    liveTimeline: "Oś operacyjna",
    noTimeline: "Brak zdarzeń operacyjnych dla tego dnia.",
    timelineTrip: "Kurs",
    timelineBooking: "Rezerwacja",
    timelineIncident: "Incydent",
    timelineEvent: "Zdarzenie",
    manifestFilter: "Filtr manifestu",
    allPassengers: "Wszyscy",
    uncheckedPassengers: "Do odprawy",
    checkedPassengers: "Odprawieni",
    exportManifest: "Eksport manifestu",
    exportDay: "Eksport dnia",
    manifestExported: "Manifest pobrany.",
    dayExported: "Raport dnia pobrany.",
    openCustomer: "Klient",
    payment: "Płatność",
    readinessPoor: "Wymaga reakcji",
    readinessOk: "Pod kontrolą",
    readinessGood: "Gotowe",
    statusLabels: {
      scheduled: "Planowany",
      boarding: "Wsiadanie",
      departed: "W drodze",
      delayed: "Opóźniony",
      arrived: "Zakończony",
      cancelled: "Anulowany",
    },
    bookingStatusLabels: {
      pending: "Oczekuje",
      paid: "Opłacona",
      cancelled: "Anulowana",
      refunded: "Zwrócona",
    },
    roleLabels: {
      customer: "Klient",
      driver: "Kierowca",
      dispatcher: "Dyspozytor",
      admin: "Admin",
    },
    incidentSeverityLabels: {
      delay: "Opóźnienie",
      technical: "Techniczny",
      passenger: "Pasażer",
      other: "Inny",
      info: "Informacja",
    },
    // Schedules page
    schedulesEyebrow: "Contbus Rozkłady",
    schedulesTitle: "Rozkłady jazdy",
    schedulesHeroBody: "Przystanki, kursy, godziny odjazdów i cennik dla trasy Lublin–Warszawa–Modlin.",
    scheduleLoadFailed: "Nie udało się pobrać danych rozkładu.",
    adminOnlyHint: "Tylko admin może edytować rozkład.",
    tabDepartures: "Odjazdy",
    tabStops: "Przystanki",
    tabFares: "Cennik",
    addDeparture: "Dodaj odjazd",
    editDeparture: "Edytuj odjazd",
    deleteDeparture: "Usuń",
    confirmDeleteDepartureTitle: "Usunąć ten odjazd?",
    confirmDeleteDepartureBody: "Tej operacji nie można cofnąć.",
    confirm: "Usuń",
    cancel: "Anuluj",
    save: "Zapisz",
    departureTime: "Godzina odjazdu",
    direction: "Kierunek",
    directionLublinWarszawa: "Lublin → Warszawa",
    directionWarszawaLublin: "Warszawa → Lublin",
    daysOfWeek: "Dni tygodnia",
    tripType: "Typ kursu",
    tripTypeRegular: "Regularny",
    tripTypeExpress: "Ekspresowy",
    isActive: "Aktywny",
    notes: "Uwagi",
    notesPlaceholder: "opcjonalnie",
    departureCreated: "Odjazd dodany.",
    departureSaved: "Odjazd zapisany.",
    departureDeleted: "Odjazd usunięty.",
    noDepartures: "Brak odjazdów.",
    dayShort: ["Pn", "Wt", "Śr", "Cz", "Pt", "So", "Nd"],
    stopName: "Nazwa",
    stopCity: "Miasto",
    stopAddress: "Adres",
    stopOrder: "Kolejność",
    stopSaved: "Przystanek zapisany.",
    stopSaveFailed: "Nie udało się zapisać przystanku.",
    fareOrigin: "Skąd \\ Dokąd",
    fareSaved: "Cena zapisana.",
    fareSaveFailed: "Nie udało się zapisać ceny.",
    noFare: "—",
    permitWarningExpired: "Zezwolenie dla trasy „{route}” wygasło {date}. Uzupełnij nowe zezwolenie.",
    permitWarningExpiringSoon: "Zezwolenie dla trasy „{route}” wygasa {date}. Przygotuj przedłużenie.",
    permitNumber: "Numer zezwolenia",
    permitValidUntil: "Ważne do",
    generateTrips: "Generuj kursy",
    generateHint: "Utwórz kursy w tabeli kursów na podstawie rozkładu odjazdów dla wybranego zakresu dat.",
    generateStartDate: "Data początkowa",
    generateEndDate: "Data końcowa",
    generateButton: "Generuj kursy",
    generating: "Generowanie...",
    generateSuccess: "Wygenerowano {count} kursów.",
    generateNoNew: "0 nowych kursów — zakres już pokryty.",
    generateFailed: "Nie udało się wygenerować kursów.",
  },
  en: {
    locale: "en-US",
    currency: "PLN",
    supabaseMissing: "Supabase is not configured for this deployment.",
    permissionsFailed: "Could not check account permissions.",
    dashboardLoadFailed: "Could not load dispatcher data.",
    loginFailed: "Could not sign in.",
    tripSaveFailed: "Could not save the trip.",
    bookingSaveFailed: "Could not save the booking.",
    roleSaveFailed: "Could not save the role.",
    bookingStatusSaved: "Booking status saved.",
    profileRoleSaved: "User role saved.",
    checkingAccessTitle: "Checking access",
    checkingAccessBody: "Loading dispatcher session.",
    operationsEyebrow: "Contbus Operations",
    dashboardTitle: "Dispatcher panel",
    navDashboard: "Dashboard",
    navSchedules: "Schedules",
    loginIntro: "Sign in with an account that has the dispatcher or admin role.",
    email: "Email",
    password: "Password",
    signingIn: "Signing in...",
    signIn: "Sign in",
    noAccessEyebrow: "No access",
    noAccessTitle: "This account is not a dispatcher",
    noAccessBody: "Ask the Supabase administrator to set the profile role to dispatcher or admin.",
    logout: "Sign out",
    heroBody:
      "Today's trips, occupancy, and sales from the same database used by the website, customer app, and driver app.",
    refresh: "Refresh",
    aggregateWarning: "The sales view is waiting for dispatcher aggregates to be activated in Supabase.",
    trips: "Trips",
    bookings: "Bookings",
    passengers: "Passengers",
    sales: "Sales",
    activeRoutes: "Active routes",
    vehicles: "Vehicles",
    notCancelled: "excluding cancelled",
    selectedDay: "for selected day",
    paidDemo: "test payments",
    staffAuthHint: "after staff auth is active",
    operations: "Operations",
    tripControl: "Trip control",
    dispatcherOps: "Dispatcher operations",
    status: "Status",
    vehicle: "Vehicle",
    driver: "Driver",
    platform: "Platform",
    assignPending: "Unassigned",
    platformPlaceholder: "e.g. Platform 3",
    tripStatusSaved: "Trip status saved.",
    vehicleAssigned: "Vehicle assigned.",
    driverAssigned: "Driver assigned.",
    platformSaved: "Platform saved.",
    revenue: "Revenue",
    incidents: "Incidents",
    tripManifest: "Trip manifest",
    noBookingsOnTrip: "No bookings on this trip.",
    chooseTrip: "Choose a trip from the operations list.",
    search: "Search",
    searchPlaceholder: "Code, email, surname...",
    noMatchingBookings: "No matching bookings.",
    access: "Access",
    userRoles: "User roles",
    unnamed: "Unnamed",
    today: "Today",
    operationalTrips: "Operational trips",
    busiest: "Highest occupancy:",
    loadingTrips: "Loading trips...",
    noTripsForDate: "No trips for this date.",
    noPlatform: "No platform",
    vehicleUnassigned: "Vehicle unassigned",
    driverUnassigned: "Driver unassigned",
    reservationsShort: "res.",
    routes: "Routes",
    salesByRoute: "Sales by route",
    routeTrips: "trips",
    recentBookings: "Recent bookings",
    noVisibleBookings: "No visible bookings.",
    passengersShort: "pax",
    checkedIn: "checked in",
    commandCenter: "Command center",
    commandCenterLead: "The key risks, crew readiness, and boarding progress in one place.",
    attentionQueue: "Needs attention",
    noAttentionItems: "No critical tasks for the selected day.",
    delayedTrips: "Delayed trips",
    missingVehicles: "Trips without vehicle",
    missingDrivers: "Trips without driver",
    missingPlatforms: "Trips without platform",
    highOccupancy: "Trips above 85% occupancy",
    activeIncidents: "Active incidents",
    fixNow: "Open trip",
    readiness: "Operational readiness",
    checkInProgress: "Check-in progress",
    fleetAssigned: "Fleet assigned",
    driversAssigned: "Drivers assigned",
    platformReady: "Platforms ready",
    liveTimeline: "Operations timeline",
    noTimeline: "No operational events for this day.",
    timelineTrip: "Trip",
    timelineBooking: "Booking",
    timelineIncident: "Incident",
    timelineEvent: "Event",
    manifestFilter: "Manifest filter",
    allPassengers: "All",
    uncheckedPassengers: "To check in",
    checkedPassengers: "Checked in",
    exportManifest: "Export manifest",
    exportDay: "Export day",
    manifestExported: "Manifest downloaded.",
    dayExported: "Day report downloaded.",
    openCustomer: "Customer",
    payment: "Payment",
    readinessPoor: "Needs action",
    readinessOk: "Under control",
    readinessGood: "Ready",
    statusLabels: {
      scheduled: "Scheduled",
      boarding: "Boarding",
      departed: "En route",
      delayed: "Delayed",
      arrived: "Completed",
      cancelled: "Cancelled",
    },
    bookingStatusLabels: {
      pending: "Pending",
      paid: "Paid",
      cancelled: "Cancelled",
      refunded: "Refunded",
    },
    roleLabels: {
      customer: "Customer",
      driver: "Driver",
      dispatcher: "Dispatcher",
      admin: "Admin",
    },
    incidentSeverityLabels: {
      delay: "Delay",
      technical: "Technical",
      passenger: "Passenger",
      other: "Other",
      info: "Information",
    },
    // Schedules page
    schedulesEyebrow: "Contbus Schedules",
    schedulesTitle: "Timetable management",
    schedulesHeroBody: "Stops, departures, and fares for the Lublin–Warszawa–Modlin route.",
    scheduleLoadFailed: "Could not load schedule data.",
    adminOnlyHint: "Only an admin can edit the schedule.",
    tabDepartures: "Departures",
    tabStops: "Stops",
    tabFares: "Fares",
    addDeparture: "Add departure",
    editDeparture: "Edit departure",
    deleteDeparture: "Delete",
    confirmDeleteDepartureTitle: "Delete this departure?",
    confirmDeleteDepartureBody: "This cannot be undone.",
    confirm: "Delete",
    cancel: "Cancel",
    save: "Save",
    departureTime: "Departure time",
    direction: "Direction",
    directionLublinWarszawa: "Lublin → Warsaw",
    directionWarszawaLublin: "Warsaw → Lublin",
    daysOfWeek: "Days of week",
    tripType: "Trip type",
    tripTypeRegular: "Regular",
    tripTypeExpress: "Express",
    isActive: "Active",
    notes: "Notes",
    notesPlaceholder: "optional",
    departureCreated: "Departure added.",
    departureSaved: "Departure saved.",
    departureDeleted: "Departure deleted.",
    noDepartures: "No departures.",
    dayShort: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    stopName: "Name",
    stopCity: "City",
    stopAddress: "Address",
    stopOrder: "Order",
    stopSaved: "Stop saved.",
    stopSaveFailed: "Could not save the stop.",
    fareOrigin: "From \\ To",
    fareSaved: "Price saved.",
    fareSaveFailed: "Could not save the price.",
    noFare: "—",
    permitWarningExpired: "The permit for route “{route}” expired on {date}. Upload a new permit.",
    permitWarningExpiringSoon: "The permit for route “{route}” expires on {date}. Prepare a renewal.",
    permitNumber: "Permit number",
    permitValidUntil: "Valid until",
    generateTrips: "Generate trips",
    generateHint: "Create trips in the live trip table from the departures timetable for the selected date range.",
    generateStartDate: "Start date",
    generateEndDate: "End date",
    generateButton: "Generate trips",
    generating: "Generating...",
    generateSuccess: "Generated {count} trips.",
    generateNoNew: "0 new trips — period already covered.",
    generateFailed: "Could not generate trips.",
  },
};

adminCopy.ua = adminCopy.pl;
