export const adminCopy = {
  pl: {
    locale: "pl-PL",
    currency: "zł",
    supabaseMissing: "Supabase nie jest skonfigurowany dla tego wdrożenia.",
    permissionsFailed: "Nie udało się sprawdzić uprawnień konta.",
    dashboardLoadFailed: "Nie udało się pobrać danych dyspozytora.",
    loginFailed: "Nie udało się zalogować.",
    tripSaveFailed: "Nie udało się zapisać kursu.",
    bookingSaveFailed: "Nie udało się zapisać rezerwacji.",
    roleSaveFailed: "Nie udało się zapisać roli.",
    bookingStatusSaved: "Status rezerwacji zapisany.",
    profileRoleSaved: "Rola użytkownika zapisana.",
    checkingAccessTitle: "Sprawdzanie dostępu",
    checkingAccessBody: "Ładowanie sesji dyspozytora.",
    operationsEyebrow: "Contbus Operacje",
    dashboardTitle: "Panel dyspozytora",
    navDashboard: "Panel",
    navSchedules: "Rozkłady",
    loginIntro: "Zaloguj się kontem z rolą dispatcher albo admin.",
    email: "Email",
    password: "Hasło",
    signingIn: "Logowanie...",
    signIn: "Zaloguj",
    noAccessEyebrow: "Brak dostępu",
    noAccessTitle: "To konto nie jest dyspozytorem",
    noAccessBody: "Poproś administratora Supabase o ustawienie roli profilu na dispatcher albo admin.",
    logout: "Wyloguj",
    heroBody:
      "Dzisiejsze kursy, obłożenie i sprzedaż z tej samej bazy, której używa strona, aplikacja klienta i aplikacja kierowcy.",
    refresh: "Odśwież",
    aggregateWarning: "Widok sprzedaży czeka na aktywację agregatów dyspozytora w Supabase.",
    trips: "Kursy",
    bookings: "Rezerwacje",
    passengers: "Pasażerowie",
    sales: "Sprzedaż",
    activeRoutes: "Aktywne trasy",
    vehicles: "Pojazdy",
    notCancelled: "bez anulowanych",
    selectedDay: "na wybrany dzień",
    paidDemo: "płatności testowe",
    staffAuthHint: "po włączeniu dostępu personelu",
    operations: "Operacje",
    tripControl: "Sterowanie kursem",
    dispatcherOps: "Operacje dyspozytora",
    status: "Status",
    vehicle: "Pojazd",
    driver: "Kierowca",
    platform: "Peron",
    assignPending: "Do przypisania",
    platformPlaceholder: "np. Peron 3",
    tripStatusSaved: "Status kursu zapisany.",
    vehicleAssigned: "Pojazd przypisany.",
    driverAssigned: "Kierowca przypisany.",
    platformSaved: "Peron zapisany.",
    revenue: "Przychód",
    incidents: "Incydenty",
    tripManifest: "Manifest kursu",
    noBookingsOnTrip: "Brak rezerwacji na tym kursie.",
    chooseTrip: "Wybierz kurs z listy operacyjnej.",
    search: "Wyszukiwarka",
    searchPlaceholder: "Kod, email, nazwisko...",
    noMatchingBookings: "Brak pasujących rezerwacji.",
    access: "Dostęp",
    userRoles: "Role użytkowników",
    unnamed: "Bez nazwy",
    today: "Dzisiaj",
    operationalTrips: "Kursy operacyjne",
    busiest: "Największe obłożenie:",
    loadingTrips: "Ładowanie kursów...",
    noTripsForDate: "Brak kursów dla tej daty.",
    noPlatform: "Bez peronu",
    vehicleUnassigned: "Pojazd do przypisania",
    driverUnassigned: "Kierowca do przypisania",
    reservationsShort: "rez.",
    routes: "Trasy",
    salesByRoute: "Sprzedaż wg tras",
    routeTrips: "kursy",
    recentBookings: "Ostatnie rezerwacje",
    noVisibleBookings: "Brak widocznych rezerwacji.",
    passengersShort: "pas.",
    checkedIn: "odprawionych",
    commandCenter: "Centrum dowodzenia",
    commandCenterLead: "Najważniejsze ryzyka, gotowość załogi i postęp odprawy w jednym miejscu.",
    attentionQueue: "Wymaga uwagi",
    noAttentionItems: "Brak krytycznych zadań dla wybranego dnia.",
    delayedTrips: "Opóźnione kursy",
    missingVehicles: "Kursy bez pojazdu",
    missingDrivers: "Kursy bez kierowcy",
    missingPlatforms: "Kursy bez peronu",
    highOccupancy: "Kursy powyżej 85% obłożenia",
    activeIncidents: "Aktywne incydenty",
    fixNow: "Otwórz kurs",
    readiness: "Gotowość operacyjna",
    checkInProgress: "Postęp odprawy",
    fleetAssigned: "Flota przypisana",
    driversAssigned: "Kierowcy przypisani",
    platformReady: "Perony gotowe",
    liveTimeline: "Oś operacyjna",
    noTimeline: "Brak zdarzeń operacyjnych dla tego dnia.",
    timelineTrip: "Kurs",
    timelineBooking: "Rezerwacja",
    timelineIncident: "Incydent",
    timelineEvent: "Zdarzenie",
    manifestFilter: "Filtr manifestu",
    allPassengers: "Wszyscy",
    uncheckedPassengers: "Do odprawy",
    checkedPassengers: "Odprawieni",
    exportManifest: "Eksport manifestu",
    exportDay: "Eksport dnia",
    manifestExported: "Manifest pobrany.",
    dayExported: "Raport dnia pobrany.",
    openCustomer: "Klient",
    payment: "Płatność",
    readinessPoor: "Wymaga reakcji",
    readinessOk: "Pod kontrolą",
    readinessGood: "Gotowe",
    // Rebooking desk
    rebookingEyebrow: "Przebookowanie",
    rebookingTitle: "Przeniesienie biletu",
    rebookingLead:
      "Znajdź bilet po kodzie lub numerze rezerwacji i przenieś całą rezerwację na inny kurs tej samej trasy z wybranego dnia.",
    ticketCodeLabel: "Kod biletu lub rezerwacji",
    ticketCodePlaceholder: "np. CB-2024-001 albo kod biletu",
    findTicket: "Znajdź",
    searchingTicket: "Szukanie...",
    ticketNotFound: "Nie znaleziono aktywnego biletu dla tego kodu.",
    ticketLookupFailed: "Nie udało się wyszukać biletu.",
    currentTripLabel: "Obecny kurs",
    targetTripLabel: "Nowy kurs (ta sama trasa)",
    chooseTargetTrip: "Wybierz kurs docelowy",
    checkTransfer: "Sprawdź",
    checkingTransfer: "Sprawdzanie...",
    transferTicket: "Przenieś",
    transferring: "Przenoszenie...",
    transferDone: "Rezerwacja przeniesiona na nowy kurs.",
    transferFailed: "Nie udało się przenieść biletu.",
    seatsFreeShort: "wolnych miejsc",
    transferResultLabels: {
      transferable: "Można przenieść",
      transferred: "Przeniesiono",
      not_found: "Nie znaleziono biletu",
      target_unavailable: "Kurs docelowy niedostępny",
      current_trip: "To jest obecny kurs tego biletu",
      no_capacity: "Brak miejsc na kursie docelowym",
      seat_conflict: "Miejsce zajęte na kursie docelowym",
      already_checked_in: "Pasażer już odprawiony — nie można przenieść",
      wrong_route: "Kurs docelowy jest na innej trasie",
    },
    // Incident filing
    fileIncident: "Zgłoś incydent",
    incidentSeverity: "Waga",
    incidentNotePlaceholder: "Co się stało? (min. 3 znaki)",
    incidentSaved: "Incydent zapisany.",
    incidentSaveFailed: "Nie udało się zapisać incydentu.",
    incidentSending: "Zapisywanie...",
    // Manifest check-in
    checkInPassenger: "Odpraw",
    undoCheckIn: "Cofnij odprawę",
    checkInSaved: "Odprawa zapisana.",
    checkInFailed: "Nie udało się zapisać odprawy.",
    // Users panel
    teamEyebrow: "Zespół i konta",
    teamTitle: "Użytkownicy",
    teamLead:
      "Kierowcy, dyspozytorzy i klienci z tej samej bazy, której używa aplikacja klienta i aplikacja kierowcy.",
    userTabTeam: "Zespół",
    userTabCustomers: "Klienci",
    userTabAll: "Wszyscy",
    userSearchPlaceholder: "Szukaj nazwiska lub telefonu...",
    noMatchingUsers: "Brak pasujących użytkowników.",
    usersCount: "{count} kont",
    tripsTodayShort: "kursów dziś",
    noTripsToday: "brak kursów dziś",
    nextTripShort: "następny",
    incidentsTodayShort: "incydentów dziś",
    bookingsTodayShort: "rezerwacji dziś",
    noBookingsToday: "brak rezerwacji dziś",
    assignToSelectedTrip: "Przypisz do kursu {time}",
    statusLabels: {
      scheduled: "Planowany",
      boarding: "Wsiadanie",
      departed: "W drodze",
      delayed: "Opóźniony",
      arrived: "Zakończony",
      cancelled: "Anulowany",
    },
    bookingStatusLabels: {
      pending: "Oczekuje",
      paid: "Opłacona",
      cancelled: "Anulowana",
      refunded: "Zwrócona",
    },
    roleLabels: {
      customer: "Klient",
      driver: "Kierowca",
      dispatcher: "Dyspozytor",
      admin: "Admin",
    },
    incidentSeverityLabels: {
      delay: "Opóźnienie",
      breakdown: "Awaria pojazdu",
      passenger: "Zdarzenie z pasażerem",
      traffic: "Utrudnienia drogowe",
      luggage: "Problem z bagażem",
      other: "Inne",
      info: "Informacja",
      warning: "Ostrzeżenie",
      critical: "Krytyczny",
    },
    // Schedules page
    schedulesEyebrow: "Contbus Rozkłady",
    schedulesTitle: "Rozkłady jazdy",
    schedulesHeroBody: "Przystanki, kursy, godziny odjazdów i cennik dla siatki Lublin–Warszawa–Chopin–Modlin.",
    scheduleLoadFailed: "Nie udało się pobrać danych rozkładu.",
    adminOnlyHint: "Tylko admin może edytować rozkład.",
    tabDepartures: "Odjazdy",
    tabStops: "Przystanki",
    tabFares: "Cennik",
    addDeparture: "Dodaj odjazd",
    editDeparture: "Edytuj odjazd",
    deleteDeparture: "Usuń",
    confirmDeleteDepartureTitle: "Usunąć ten odjazd?",
    confirmDeleteDepartureBody: "Tej operacji nie można cofnąć.",
    confirm: "Usuń",
    cancel: "Anuluj",
    save: "Zapisz",
    departureTime: "Godzina odjazdu",
    direction: "Kierunek",
    allDirections: "Wszystkie kierunki",
    directionLublinWarszawa: "Lublin → Warszawa",
    directionWarszawaLublin: "Warszawa → Lublin",
    directionLublinChopin: "Lublin → Lotnisko Chopina",
    directionChopinLublin: "Lotnisko Chopina → Lublin",
    directionLublinModlin: "Lublin → Lotnisko Modlin",
    directionModlinLublin: "Lotnisko Modlin → Lublin",
    directionWarszawaChopin: "Warszawa → Lotnisko Chopina",
    directionChopinWarszawa: "Lotnisko Chopina → Warszawa",
    directionWarszawaModlin: "Warszawa → Lotnisko Modlin",
    directionModlinWarszawa: "Lotnisko Modlin → Warszawa",
    directionChopinModlin: "Lotnisko Chopina → Lotnisko Modlin",
    directionModlinChopin: "Lotnisko Modlin → Lotnisko Chopina",
    daysOfWeek: "Dni tygodnia",
    tripType: "Typ kursu",
    tripTypeRegular: "Regularny",
    tripTypeExpress: "Ekspresowy",
    isActive: "Aktywny",
    notes: "Uwagi",
    notesPlaceholder: "opcjonalnie",
    departureCreated: "Odjazd dodany.",
    departureSaved: "Odjazd zapisany.",
    departureDeleted: "Odjazd usunięty.",
    noDepartures: "Brak odjazdów.",
    dayShort: ["Pn", "Wt", "Śr", "Cz", "Pt", "So", "Nd"],
    stopName: "Nazwa",
    stopCity: "Miasto",
    stopAddress: "Adres",
    stopOrder: "Kolejność",
    stopSaved: "Przystanek zapisany.",
    stopSaveFailed: "Nie udało się zapisać przystanku.",
    fareOrigin: "Skąd \\ Dokąd",
    fareSaved: "Cena zapisana.",
    fareSaveFailed: "Nie udało się zapisać ceny.",
    noFare: "—",
    permitWarningExpired: "Zezwolenie dla trasy „{route}” wygasło {date}. Uzupełnij nowe zezwolenie.",
    permitWarningExpiringSoon: "Zezwolenie dla trasy „{route}” wygasa {date}. Przygotuj przedłużenie.",
    permitNumber: "Numer zezwolenia",
    permitValidUntil: "Ważne do",
    generateTrips: "Generuj kursy",
    generateHint: "Utwórz kursy w tabeli kursów na podstawie rozkładu odjazdów dla wybranego zakresu dat.",
    generateStartDate: "Data początkowa",
    generateEndDate: "Data końcowa",
    generateButton: "Generuj kursy",
    generating: "Generowanie...",
    generateSuccess: "Wygenerowano {count} kursów.",
    generateNoNew: "0 nowych kursów — zakres już pokryty.",
    generateFailed: "Nie udało się wygenerować kursów.",
    tabTrips: "Kursy",
    tripsLoadFailed: "Nie udało się pobrać kursów.",
    tripAssignSaved: "Przypisanie zapisane.",
    tripAssignFailed: "Nie udało się zapisać przypisania.",
    dateFrom: "Od",
    dateTo: "Do",
    tripDate: "Data",
    tripTime: "Godzina",
    tripRoute: "Trasa",
    noTrips: "Brak kursów w wybranym zakresie dat.",
    liveOn: "Na żywo",
    liveOff: "Brak połączenia na żywo",
    liveOffHint: "Dane mogą być nieaktualne. Odśwież ręcznie.",
    lastUpdate: "Aktualizacja",
    sortBy: "Sortuj",
    sortTime: "Godzina",
    sortOccupancy: "Obłożenie",
    sortRoute: "Trasa",
    sortStatus: "Status",
    selectTrip: "Zaznacz kurs",
    selectedCount: "zaznaczonych",
    clearSelection: "Wyczyść",
    selectAllVisible: "Zaznacz widoczne",
    bulkAssign: "Przypisz zbiorczo",
    bulkVehicle: "Pojazd dla zaznaczonych",
    bulkDriver: "Kierowca dla zaznaczonych",
    bulkApplied: "Zapisano {count} kursów.",
    bulkFailed: "Nie udało się zapisać {count} kursów.",
    bulkWorking: "Zapisywanie...",
    callDriver: "Zadzwoń",
    noDriverPhone: "Brak numeru telefonu",
    tripSearchPlaceholder: "Szukaj godziny, trasy lub przypisania...",
    prevPage: "Poprzednia",
    nextPage: "Następna",
    pageOf: "Strona {page} z {count}",
    filterTripsLabel: "Filtruj kursy operacyjne",
    tripStatusLabel: "Status kursu",
    allStatuses: "Wszystkie statusy",
    fleetCorridors: "Korytarze operacyjne floty",
    activeEnRoute: "w trasie",
    punctuality: "Punktualność",
    printManifest: "Drukuj manifest",
    printManifestSheet: "Drukuj arkusz inspekcyjny",
    timetableExport: "Pobierz Rozkład Jazdy (PDF)",
    carrierInspectionRoster: "Protokół odprawy i inspekcji przewozu",
    dispatcherSignature: "Podpis dyspozytora / kierowcy",
    inspectorNotes: "Uwagi z kontroli / pieczęć",
    officialTimetable: "Oficjalny Rozkład Jazdy Contbus",
    seatNumber: "Miejsce",
    ticketCode: "Kod biletu",
    passengerName: "Pasażer",
    stopDestination: "Przystanek docelowy",
    checkInState: "Status odprawy",
    close: "Zamknij",
    print: "Drukuj",
  },
  en: {
    locale: "en-US",
    currency: "PLN",
    supabaseMissing: "Supabase is not configured for this deployment.",
    permissionsFailed: "Could not check account permissions.",
    dashboardLoadFailed: "Could not load dispatcher data.",
    loginFailed: "Could not sign in.",
    tripSaveFailed: "Could not save the trip.",
    bookingSaveFailed: "Could not save the booking.",
    roleSaveFailed: "Could not save the role.",
    bookingStatusSaved: "Booking status saved.",
    profileRoleSaved: "User role saved.",
    checkingAccessTitle: "Checking access",
    checkingAccessBody: "Loading dispatcher session.",
    operationsEyebrow: "Contbus Operations",
    dashboardTitle: "Dispatcher Dashboard",
    navDashboard: "Dashboard",
    navSchedules: "Schedules",
    loginIntro: "Sign in with an account having the dispatcher or admin role.",
    email: "Email",
    password: "Password",
    signingIn: "Signing in...",
    signIn: "Sign in",
    noAccessEyebrow: "Access denied",
    noAccessTitle: "This account is not a dispatcher",
    noAccessBody: "Ask your Supabase administrator to set your profile role to dispatcher or admin.",
    logout: "Sign out",
    heroBody:
      "Today's trips, occupancy, and sales from the same database powering the website, customer app, and driver app.",
    refresh: "Refresh",
    aggregateWarning: "Sales view is waiting for dispatcher aggregates activation in Supabase.",
    trips: "Trips",
    bookings: "Bookings",
    passengers: "Passengers",
    sales: "Sales",
    activeRoutes: "Active routes",
    vehicles: "Vehicles",
    notCancelled: "excluding cancelled",
    selectedDay: "for selected date",
    paidDemo: "demo payments",
    staffAuthHint: "when staff access is enabled",
    operations: "Operations",
    tripControl: "Trip control",
    dispatcherOps: "Dispatcher operations",
    status: "Status",
    vehicle: "Vehicle",
    driver: "Driver",
    platform: "Platform",
    assignPending: "To assign",
    platformPlaceholder: "e.g. Platform 3",
    tripStatusSaved: "Trip status saved.",
    vehicleAssigned: "Vehicle assigned.",
    driverAssigned: "Driver assigned.",
    platformSaved: "Platform saved.",
    revenue: "Revenue",
    incidents: "Incidents",
    tripManifest: "Trip manifest",
    noBookingsOnTrip: "No bookings on this trip.",
    chooseTrip: "Choose a trip from the operational list.",
    search: "Search",
    searchPlaceholder: "Code, email, last name...",
    noMatchingBookings: "No matching bookings.",
    access: "Access",
    userRoles: "User roles",
    unnamed: "Unnamed",
    today: "Today",
    operationalTrips: "Operational trips",
    busiest: "Highest occupancy:",
    loadingTrips: "Loading trips...",
    noTripsForDate: "No trips for this date.",
    noPlatform: "No platform",
    vehicleUnassigned: "Vehicle to assign",
    driverUnassigned: "Driver to assign",
    reservationsShort: "res.",
    routes: "Routes",
    salesByRoute: "Sales by route",
    routeTrips: "trips",
    recentBookings: "Recent bookings",
    noVisibleBookings: "No visible bookings.",
    passengersShort: "pax",
    checkedIn: "checked in",
    commandCenter: "Command center",
    commandCenterLead: "Key risks, crew readiness, and check-in progress in one place.",
    attentionQueue: "Needs attention",
    noAttentionItems: "No critical tasks for the selected day.",
    delayedTrips: "Delayed trips",
    missingVehicles: "Trips without vehicle",
    missingDrivers: "Trips without driver",
    missingPlatforms: "Trips without platform",
    highOccupancy: "Trips above 85% occupancy",
    activeIncidents: "Active incidents",
    fixNow: "Open trip",
    readiness: "Operational readiness",
    checkInProgress: "Check-in progress",
    fleetAssigned: "Fleet assigned",
    driversAssigned: "Drivers assigned",
    platformReady: "Platforms ready",
    liveTimeline: "Operations timeline",
    noTimeline: "No operational events for this day.",
    timelineTrip: "Trip",
    timelineBooking: "Booking",
    timelineIncident: "Incident",
    timelineEvent: "Event",
    manifestFilter: "Manifest filter",
    allPassengers: "All",
    uncheckedPassengers: "To check in",
    checkedPassengers: "Checked in",
    exportManifest: "Export manifest",
    exportDay: "Export day",
    manifestExported: "Manifest downloaded.",
    dayExported: "Day report downloaded.",
    openCustomer: "Customer",
    payment: "Payment",
    readinessPoor: "Needs action",
    readinessOk: "Under control",
    readinessGood: "Ready",
    // Rebooking desk
    rebookingEyebrow: "Rebooking",
    rebookingTitle: "Ticket transfer",
    rebookingLead:
      "Find a ticket by ticket code or booking reference and move the whole booking to another trip on the same route on the selected day.",
    ticketCodeLabel: "Ticket or booking code",
    ticketCodePlaceholder: "e.g. CB-2024-001 or a ticket code",
    findTicket: "Find",
    searchingTicket: "Searching...",
    ticketNotFound: "No active ticket found for this code.",
    ticketLookupFailed: "Ticket lookup failed.",
    currentTripLabel: "Current trip",
    targetTripLabel: "New trip (same route)",
    chooseTargetTrip: "Choose target trip",
    checkTransfer: "Check",
    checkingTransfer: "Checking...",
    transferTicket: "Transfer",
    transferring: "Transferring...",
    transferSuccess: "Ticket transferred.",
    transferFailed: "Could not transfer ticket.",
    transferSummaryAvailable: "Free seats: {available}. Click transfer to move the passenger.",
    transferSummaryNoCapacity: "No capacity on target trip ({available} seats available).",
    transferSummaryTargetClosed: "Target trip cannot accept transfers (status: {status}).",
    transferSummaryWrongRoute: "Target trip is on a different route.",
    transferSummarySameTrip: "Choose a different departure on the same route.",
    seatsFreeShort: "seats free",
    transferResultLabels: {
      transferable: "Ready to transfer",
      transferred: "Transferred",
      not_found: "Ticket not found",
      target_unavailable: "Target trip unavailable",
      current_trip: "Ticket is already on this trip",
      no_capacity: "No seats left on the target trip",
      seat_conflict: "Seat already taken on the target trip",
      already_checked_in: "Passenger already checked in — cannot transfer",
      wrong_route: "Target trip is on a different route",
    },
    // Incident filing
    fileIncident: "Report incident",
    incidentSeverity: "Severity",
    incidentNotePlaceholder: "Describe operational incident...",
    incidentSaved: "Incident reported.",
    incidentSaveFailed: "Could not report incident.",
    incidentSending: "Saving...",
    // Manifest check-in
    checkInPassenger: "Check in passenger",
    undoCheckIn: "Undo check-in",
    checkInSaved: "Check-in saved.",
    checkInFailed: "Could not save check-in.",
    // Users panel
    teamEyebrow: "Team & accounts",
    teamTitle: "Users",
    teamLead:
      "Drivers, dispatchers, and customers from the same database used by the customer and driver apps.",
    userTabTeam: "Team",
    userTabCustomers: "Customers",
    userTabAll: "All",
    userSearchPlaceholder: "Search name or phone...",
    noMatchingUsers: "No matching users.",
    usersCount: "{count} accounts",
    tripsTodayShort: "trips today",
    noTripsToday: "no trips today",
    nextTripShort: "next",
    incidentsTodayShort: "incidents today",
    bookingsTodayShort: "bookings today",
    noBookingsToday: "no bookings today",
    assignToSelectedTrip: "Assign to the {time} trip",
    statusLabels: {
      scheduled: "Scheduled",
      boarding: "Boarding",
      departed: "En route",
      delayed: "Delayed",
      arrived: "Completed",
      cancelled: "Cancelled",
    },
    tripStatusLabels: {
      scheduled: "Scheduled",
      preparing: "Preparing",
      boarding: "Boarding",
      enroute: "En route",
      delayed: "Delayed",
      arrived: "Completed",
      cancelled: "Cancelled",
    },
    bookingStatusLabels: {
      pending: "Pending",
      paid: "Paid",
      cancelled: "Cancelled",
      refunded: "Refunded",
    },
    roleLabels: {
      customer: "Customer",
      driver: "Driver",
      dispatcher: "Dispatcher",
      admin: "Admin",
    },
    incidentSeverityLabels: {
      delay: "Delay",
      breakdown: "Vehicle breakdown",
      passenger: "Passenger incident",
      traffic: "Traffic disruption",
      luggage: "Luggage issue",
      other: "Other",
      info: "Information",
      warning: "Warning",
      critical: "Critical",
    },
    // Schedules page
    schedulesEyebrow: "Contbus Schedules",
    schedulesTitle: "Timetable management",
    schedulesHeroBody: "Stops, departures, and fares for the Lublin–Warsaw–Chopin–Modlin network.",
    scheduleLoadFailed: "Could not load schedule data.",
    adminOnlyHint: "Only an admin can edit the schedule.",
    tabDepartures: "Departures",
    tabStops: "Stops",
    tabFares: "Fares",
    addDeparture: "Add departure",
    editDeparture: "Edit departure",
    deleteDeparture: "Delete",
    confirmDeleteDepartureTitle: "Delete this departure?",
    confirmDeleteDepartureBody: "This cannot be undone.",
    confirm: "Delete",
    cancel: "Cancel",
    save: "Save",
    departureTime: "Departure time",
    direction: "Direction",
    allDirections: "All directions",
    directionLublinWarszawa: "Lublin → Warsaw",
    directionWarszawaLublin: "Warsaw → Lublin",
    directionLublinChopin: "Lublin → Chopin Airport",
    directionChopinLublin: "Chopin Airport → Lublin",
    directionLublinModlin: "Lublin → Modlin Airport",
    directionModlinLublin: "Modlin Airport → Lublin",
    directionWarszawaChopin: "Warsaw → Chopin Airport",
    directionChopinWarszawa: "Chopin Airport → Warsaw",
    directionWarszawaModlin: "Warsaw → Modlin Airport",
    directionModlinWarszawa: "Modlin Airport → Warsaw",
    directionChopinModlin: "Chopin Airport → Modlin Airport",
    directionModlinChopin: "Modlin Airport → Chopin Airport",
    daysOfWeek: "Days of week",
    tripType: "Trip type",
    tripTypeRegular: "Regular",
    tripTypeExpress: "Express",
    isActive: "Active",
    notes: "Notes",
    notesPlaceholder: "optional",
    departureCreated: "Departure added.",
    departureSaved: "Departure saved.",
    departureDeleted: "Departure deleted.",
    noDepartures: "No departures.",
    dayShort: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    stopName: "Name",
    stopCity: "City",
    stopAddress: "Address",
    stopOrder: "Order",
    stopSaved: "Stop saved.",
    stopSaveFailed: "Could not save the stop.",
    fareOrigin: "From \\ To",
    fareSaved: "Price saved.",
    fareSaveFailed: "Could not save the price.",
    noFare: "—",
    permitWarningExpired: "The permit for route “{route}” expired on {date}. Upload a new permit.",
    permitWarningExpiringSoon: "The permit for route “{route}” expires on {date}. Prepare a renewal.",
    permitNumber: "Permit number",
    permitValidUntil: "Valid until",
    generateTrips: "Generate trips",
    generateHint: "Create trips in the live trip table from the departures timetable for the selected date range.",
    generateStartDate: "Start date",
    generateEndDate: "End date",
    generateButton: "Generate trips",
    generating: "Generating...",
    generateSuccess: "Generated {count} trips.",
    generateNoNew: "0 new trips — period already covered.",
    generateFailed: "Could not generate trips.",
    tabTrips: "Trips",
    tripsLoadFailed: "Could not load trips.",
    tripAssignSaved: "Assignment saved.",
    tripAssignFailed: "Could not save the assignment.",
    dateFrom: "From",
    dateTo: "To",
    tripDate: "Date",
    tripTime: "Time",
    tripRoute: "Route",
    noTrips: "No trips in the selected date range.",
    liveOn: "Live",
    liveOff: "Not live",
    liveOffHint: "Data may be stale. Refresh manually.",
    lastUpdate: "Updated",
    sortBy: "Sort",
    sortTime: "Time",
    sortOccupancy: "Occupancy",
    sortRoute: "Route",
    sortStatus: "Status",
    selectTrip: "Select trip",
    selectedCount: "selected",
    clearSelection: "Clear",
    selectAllVisible: "Select visible",
    bulkAssign: "Bulk assign",
    bulkVehicle: "Vehicle for selected",
    bulkDriver: "Driver for selected",
    bulkApplied: "Saved {count} trips.",
    bulkFailed: "Could not save {count} trips.",
    bulkWorking: "Saving...",
    callDriver: "Call",
    noDriverPhone: "No phone number",
    tripSearchPlaceholder: "Search time, route, or assignment...",
    prevPage: "Previous",
    nextPage: "Next",
    pageOf: "Page {page} of {count}",
    filterTripsLabel: "Filter operational trips",
    tripStatusLabel: "Trip status",
    allStatuses: "All statuses",
    fleetCorridors: "Fleet operational corridors",
    activeEnRoute: "en route",
    punctuality: "Punctuality",
    printManifest: "Print manifest",
    printManifestSheet: "Print inspection sheet",
    timetableExport: "Download Timetable (PDF)",
    carrierInspectionRoster: "Passenger Boarding & Inspection Sheet",
    dispatcherSignature: "Dispatcher / Driver signature",
    inspectorNotes: "Inspection notes / Stamp",
    officialTimetable: "Official Contbus Timetable",
    seatNumber: "Seat",
    ticketCode: "Ticket code",
    passengerName: "Passenger",
    stopDestination: "Destination stop",
    checkInState: "Check-in status",
    close: "Close",
    print: "Print",
  },
  uk: {
    locale: "uk-UA",
    currency: "грн",
    supabaseMissing: "Supabase не налаштовано для цього середовища.",
    permissionsFailed: "Не вдалося перевірити права доступу.",
    dashboardLoadFailed: "Не вдалося завантажити дані диспетчера.",
    loginFailed: "Не вдалося увійти.",
    tripSaveFailed: "Не вдалося зберегти рейс.",
    bookingSaveFailed: "Не вдалося зберегти бронювання.",
    roleSaveFailed: "Не вдалося зберегти роль.",
    bookingStatusSaved: "Статус бронювання збережено.",
    profileRoleSaved: "Роль користувача збережена.",
    checkingAccessTitle: "Перевірка доступу",
    checkingAccessBody: "Завантаження сесії диспетчера.",
    operationsEyebrow: "Contbus Операції",
    dashboardTitle: "Панель диспетчера",
    navDashboard: "Панель",
    navSchedules: "Розклади",
    loginIntro: "Увійдіть з акаунтом диспетчера або адміністратора.",
    email: "Email",
    password: "Пароль",
    signingIn: "Вхід...",
    signIn: "Увійти",
    noAccessEyebrow: "Доступ заборонено",
    noAccessTitle: "Цей акаунт не має прав диспетчера",
    noAccessBody: "Зверніться до адміністратора для надання прав.",
    logout: "Вийти",
    heroBody:
      "Сьогоднішні рейси, завантаженість та продажі з єдиної бази даних.",
    refresh: "Оновити",
    aggregateWarning: "Очікується активація диспетчерських агрегатів у Supabase.",
    trips: "Рейси",
    bookings: "Бронювання",
    passengers: "Пасажири",
    sales: "Продажі",
    activeRoutes: "Активні маршрути",
    vehicles: "Транспорт",
    notCancelled: "без скасованих",
    selectedDay: "на обраний день",
    paidDemo: "тестові платежі",
    staffAuthHint: "після активації доступу персоналу",
    operations: "Операції",
    tripControl: "Керування рейсом",
    dispatcherOps: "Дії диспетчера",
    status: "Статус",
    vehicle: "Автобус",
    driver: "Водій",
    platform: "Перон",
    assignPending: "До призначення",
    platformPlaceholder: "напр. Перон 3",
    tripStatusSaved: "Статус рейсу збережено.",
    vehicleAssigned: "Автобус призначено.",
    driverAssigned: "Водія призначено.",
    platformSaved: "Перон збережено.",
    revenue: "Дохід",
    incidents: "Інциденти",
    tripManifest: "Маніфест рейсу",
    noBookingsOnTrip: "Немає бронювань на цей рейс.",
    chooseTrip: "Оберіть рейс зі списку.",
    search: "Пошук",
    searchPlaceholder: "Код, email, прізвище...",
    noMatchingBookings: "Нічого не знайдено.",
    access: "Доступ",
    userRoles: "Ролі користувачів",
    unnamed: "Без імені",
    today: "Сьогодні",
    operationalTrips: "Операційні рейси",
    busiest: "Найбільше завантаження:",
    loadingTrips: "Завантаження рейсів...",
    noTripsForDate: "Немає рейсів на цю дату.",
    noPlatform: "Без перону",
    vehicleUnassigned: "Автобус не призначено",
    driverUnassigned: "Водій не призначений",
    reservationsShort: "брон.",
    routes: "Маршрути",
    salesByRoute: "Продажі за маршрутами",
    routeTrips: "рейси",
    recentBookings: "Останні бронювання",
    noVisibleBookings: "Немає видимих бронювань.",
    passengersShort: "пас.",
    checkedIn: "оформлено",
    commandCenter: "Командний центр",
    commandCenterLead: "Критичні завдання, готовність екіпажу та статус посадки в одному місці.",
    attentionQueue: "Потребує уваги",
    noAttentionItems: "Немає критичних завдань на обраний день.",
    delayedTrips: "Затримані рейси",
    missingVehicles: "Рейси без автобуса",
    missingDrivers: "Рейси без водія",
    missingPlatforms: "Рейси без перону",
    highOccupancy: "Рейси з завантаженням понад 85%",
    activeIncidents: "Активні інциденти",
    fixNow: "Відкрити рейс",
    readiness: "Операційна готовність",
    checkInProgress: "Прогрес посадки",
    fleetAssigned: "Автобуси призначені",
    driversAssigned: "Водії призначені",
    platformReady: "Перони готові",
    liveTimeline: "Хронологія подій",
    noTimeline: "Немає подій за цей день.",
    timelineTrip: "Рейс",
    timelineBooking: "Бронювання",
    timelineIncident: "Інцидент",
    timelineEvent: "Подія",
    manifestFilter: "Фільтр маніфесту",
    allPassengers: "Всі",
    uncheckedPassengers: "Очікують",
    checkedPassengers: "Оформлені",
    exportManifest: "Експорт маніфесту",
    exportDay: "Експорт дня",
    manifestExported: "Маніфест завантажено.",
    dayExported: "Звіт дня завантажено.",
    openCustomer: "Клієнт",
    payment: "Оплата",
    readinessPoor: "Потрібна дія",
    readinessOk: "Під контролем",
    readinessGood: "Готово",
    rebookingEyebrow: "Перебронювання",
    rebookingTitle: "Перенесення квитка",
    rebookingLead: "Знайти квиток за номером та перенести на інший рейс того ж маршруту.",
    ticketCodeLabel: "Номер квитка або бронювання",
    ticketCodePlaceholder: "напр. CB-2024-001",
    findTicket: "Знайти",
    searchingTicket: "Пошук...",
    ticketNotFound: "Квиток не знайдено.",
    ticketLookupFailed: "Помилка пошуку квитка.",
    currentTripLabel: "Поточний рейс",
    targetTripLabel: "Новий рейс",
    chooseTargetTrip: "Оберіть новий рейс",
    checkTransfer: "Перевірити",
    checkingTransfer: "Перевірка...",
    transferTicket: "Перенести",
    transferring: "Перенесення...",
    transferSuccess: "Квиток перенесено.",
    transferFailed: "Не вдалося перенести квиток.",
    transferSummaryAvailable: "Вільних місць: {available}. Натисніть Перенести.",
    transferSummaryNoCapacity: "Немає вільних місць ({available}).",
    transferSummaryTargetClosed: "Рейс закритий для змін (статус: {status}).",
    transferSummaryWrongRoute: "Рейс на інший маршрут.",
    transferSummarySameTrip: "Оберіть інший рейс того самого напрямку.",
    seatsFreeShort: "вільних місць",
    transferResultLabels: {
      transferable: "Можна перенести",
      transferred: "Перенесено",
      not_found: "Квиток не знайдено",
      target_unavailable: "Рейс недоступний",
      current_trip: "Це поточний рейс",
      no_capacity: "Немає місць",
      seat_conflict: "Місце зайнято",
      already_checked_in: "Пасажир вже оформлений",
      wrong_route: "Рейс на інший маршрут",
    },
    undoCheckIn: "Скасувати посадку",
    checkInPassenger: "Оформити пасажира",
    checkInSaved: "Оформлення збережено.",
    checkInFailed: "Помилка збереження.",
    incidentSeverity: "Важливість",
    incidentNotePlaceholder: "Опишіть подію...",
    incidentSending: "Надсилання...",
    fileIncident: "Повідомити про інцидент",
    incidentSaved: "Інцидент зареєстровано.",
    incidentSaveFailed: "Не вдалося зареєструвати інцидент.",
    tripStatusLabels: {
      scheduled: "Запланований",
      preparing: "Підготовка",
      boarding: "Посадка",
      enroute: "У дорозі",
      delayed: "Затримка",
      arrived: "Завершено",
      cancelled: "Скасовано",
    },
    bookingStatusLabels: {
      pending: "Очікує",
      paid: "Оплачено",
      cancelled: "Скасовано",
      refunded: "Повернено",
    },
    roleLabels: {
      customer: "Клієнт",
      driver: "Водій",
      dispatcher: "Диспетчер",
      admin: "Адміністратор",
    },
    incidentSeverityLabels: {
      delay: "Затримка",
      breakdown: "Поломка автобуса",
      passenger: "Інцидент з пасажиром",
      traffic: "Дорожні ускладнення",
      luggage: "Проблема з багажем",
      other: "Інше",
      info: "Інформація",
      warning: "Попередження",
      critical: "Критичний",
    },
    schedulesEyebrow: "Contbus Розклади",
    schedulesTitle: "Керування розкладом",
    schedulesHeroBody: "Зупинки, рейси та тарифи для мережі Люблін–Варшава–Шопен–Модлін.",
    scheduleLoadFailed: "Не вдалося завантажити дані розкладу.",
    adminOnlyHint: "Тільки адміністратор може редагувати розклад.",
    tabDepartures: "Відправлення",
    tabStops: "Зупинки",
    tabFares: "Тарифи",
    addDeparture: "Додати відправлення",
    editDeparture: "Редагувати відправлення",
    deleteDeparture: "Видалити",
    confirmDeleteDepartureTitle: "Видалити відправлення?",
    confirmDeleteDepartureBody: "Цю дію не можна скасувати.",
    confirm: "Видалити",
    cancel: "Скасувати",
    save: "Зберегти",
    departureTime: "Час відправлення",
    direction: "Напрямок",
    allDirections: "Всі напрямки",
    directionLublinWarszawa: "Люблін → Варшава",
    directionWarszawaLublin: "Варшава → Люблін",
    directionLublinChopin: "Люблін → Аеропорт Шопен",
    directionChopinLublin: "Аеропорт Шопен → Люблін",
    directionLublinModlin: "Люблін → Аеропорт Модлін",
    directionModlinLublin: "Аеропорт Модлін → Люблін",
    directionWarszawaChopin: "Варшава → Аеропорт Шопен",
    directionChopinWarszawa: "Аеропорт Шопен → Варшава",
    directionWarszawaModlin: "Варшава → Аеропорт Модлін",
    directionModlinWarszawa: "Аеропорт Модлін → Варшава",
    directionChopinModlin: "Аеропорт Шопен → Аеропорт Модлін",
    directionModlinChopin: "Аеропорт Модлін → Аеропорт Шопен",
    daysOfWeek: "Дні тижня",
    tripType: "Тип рейсу",
    tripTypeRegular: "Регулярний",
    tripTypeExpress: "Експрес",
    isActive: "Активний",
    notes: "Примітки",
    notesPlaceholder: "необов'язково",
    departureCreated: "Відправлення додано.",
    departureSaved: "Відправлення збережено.",
    departureDeleted: "Відправлення видалено.",
    noDepartures: "Немає відправлень.",
    dayShort: ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Нд"],
    stopName: "Назва",
    stopCity: "Місто",
    stopAddress: "Адреса",
    stopOrder: "Порядок",
    stopSaved: "Зупинку збережено.",
    stopSaveFailed: "Не вдалося зберегти зупинку.",
    fareOrigin: "Звідки \\ Куди",
    fareSaved: "Ціну збережено.",
    fareSaveFailed: "Не вдалося зберегти ціну.",
    noFare: "—",
    permitWarningExpired: "Дозвіл на маршрут “{route}” закінчився {date}.",
    permitWarningExpiringSoon: "Дозвіл на маршрут “{route}” закінчується {date}.",
    permitNumber: "Номер дозволу",
    permitValidUntil: "Дійсний до",
    generateTrips: "Згенерувати рейси",
    generateHint: "Створити рейси в таблиці на обраний період.",
    generateStartDate: "Початкова дата",
    generateEndDate: "Кінцева дата",
    generateButton: "Згенерувати",
    generating: "Генерація...",
    generateSuccess: "Згенеровано {count} рейсів.",
    generateNoNew: "0 нових рейсів — період вже заповнено.",
    generateFailed: "Не вдалося згенерувати рейси.",
    tabTrips: "Рейси",
    tripsLoadFailed: "Не вдалося завантажити рейси.",
    tripAssignSaved: "Призначення збережено.",
    tripAssignFailed: "Не вдалося зберегти призначення.",
    dateFrom: "З",
    dateTo: "До",
    tripDate: "Дата",
    tripTime: "Час",
    tripRoute: "Маршрут",
    noTrips: "Немає рейсів у вибраному діапазоні.",
    liveOn: "Live",
    liveOff: "Не Live",
    liveOffHint: "Дані можуть бути застарілими.",
    lastUpdate: "Оновлено",
    sortBy: "Сортувати",
    sortTime: "Час",
    sortOccupancy: "Завантаженість",
    sortRoute: "Маршрут",
    sortStatus: "Статус",
    selectTrip: "Обрати рейс",
    selectedCount: "обрано",
    clearSelection: "Очистити",
    selectAllVisible: "Обрати всі видимі",
    bulkAssign: "Масове призначення",
    bulkVehicle: "Автобус для обраних",
    bulkDriver: "Водій для обраних",
    bulkApplied: "Збережено {count} рейсів.",
    bulkFailed: "Помилка збереження {count} рейсів.",
    bulkWorking: "Збереження...",
    callDriver: "Зателефонувати",
    noDriverPhone: "Немає номера телефону",
    tripSearchPlaceholder: "Пошук часу, маршруту або призначення...",
    prevPage: "Попередня",
    nextPage: "Наступна",
    pageOf: "Сторінка {page} з {count}",
    filterTripsLabel: "Фільтрувати операційні рейси",
    tripStatusLabel: "Статус рейсу",
    allStatuses: "Всі статуси",
    fleetCorridors: "Операційні коридори флоту",
    activeEnRoute: "у дорозі",
    punctuality: "Пунктуальність",
    printManifest: "Друк маніфесту",
    printManifestSheet: "Роздрукувати відомість",
    timetableExport: "Завантажити розклад (PDF)",
    carrierInspectionRoster: "Відомість посадки та інспекції перевезення",
    dispatcherSignature: "Підпис диспетчера / водія",
    inspectorNotes: "Примітки контролю / печатка",
    officialTimetable: "Офіційний розклад руху Contbus",
    seatNumber: "Місце",
    ticketCode: "Код квитка",
    passengerName: "Пасажир",
    stopDestination: "Зупинка",
    checkInState: "Статус посадки",
    close: "Закрити",
    print: "Друк",
  },
};

adminCopy.ua = adminCopy.uk;
